openapi: "3.0.3"
info:
  title: Product Microservice

  version: "1.0.0"
  # description:
servers:
  - url: http://localhost:8081
paths:


  /products:
    get:
      tags:
        - Products
      summary: Getting all products
      description: Getting list of all products
      parameters:
        - name: 'searchBody'
          in: query
          required: false
          description: search result for products, can contain product name, vendor name, description, 
          example: "abc"
          schema:
            type: string 
      responses:
        '200':
          description: details found and returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSchema'
        '404':
            description: Products not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: No Products found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: server not working
    post:
      tags:
        - Products
      summary: Adding of new product by vendor
      description: Adding new product by vendor
      parameters:
        - name: 'uuid'
          in: query
          required: true
          description: uuid of vendor
          example: "00a6fa25-df29-4701-9077-557932591766"
          schema:
            type: string
      requestBody:
        description: Request to create new product
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductSchema'
        required: true
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateProductSchema'
        '401':
          description: Vendor not authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Vendor not authorized
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: server not working
    put:
      tags:
        - Products
      parameters:
        - name: 'uuid'
          in: query
          required: true
          description: The uuid of product
          example: "00a6fa25-df29-4701-9077-557932591766"
          schema:
            type: string
        - name: 'uuid'
          in: query
          required: true
          description: The uuid of vendor
          example: "00a6fa25-df29-4701-9077-557932591766"
          schema:
            type: string
      summary: Edit the Product details
      description: Edit the Product details 
      requestBody:
        description: Request to edit product details
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditProductRequest'
        required: true
      responses:
        '200':
          description: Product details updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product details edited successfully.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Product not found
        '401':
          description: Vendor not authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Vendor not authorized
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided uuid is not valid
        
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  
  /products/{uuid}:
    get:
      tags:
        - Products
      parameters:
        - name: 'uuid'
          in: path
          required: true
          description: The uuid of product
          example: "00a6fa25-df29-4701-9077-557932591766"
          schema:
            type: string
      summary: Getting details of a product
      description: Getting details of a product
      responses:
        '200':
          description: details of a particular product found and returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSchema'
        '404':
            description: Product not found
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      example: Product not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: server not working

    
    
    delete:
      tags:
        - Products
      parameters:
        - name: 'uuid'
          in: path
          required: true
          description: The uuid of product
          example: "00a6fa25-df29-4701-9077-557932591766"
          schema:
            type: string
        - name: 'uuid'
          in: query
          required: true
          description: The uuid of vendor
          example: "00a6fa25-df29-4701-9077-557932591766"
          schema:
            type: string
      summary: delete the product 
      description: delete the product  
      responses:
        '200':
          description: product deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: product deleted successfully.
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Product not found
        '400':
          description: Invalid request 
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: The provided uuid is not valid
        '401':
          description: Vendor not authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Vendor not authorized

        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string


components:
  schemas:
    ProductSchema:
      type: object
      properties:
        uuid:
          type: string
          example: "00a6fa25-df29-4701-9077-557932591766"
        category:
          type: string
        name:
          type: string
          example: "name"
        description: 
          type: string
          example: "description"
        stock:
          type: number
          example: '12'
        vendor:
          type: string
          example: "00a6fa25"
        productImages:
          type: array
          items: 
            type: string
      required:
        - uuid
        - category
        - name
        - description
        - vendor
        - stock

    CreateProductSchema:
      type: object
      properties:
        category:
          type: string
        name:
          type: string
          example: "name"
        description: 
          type: string
          example: "description"
        stock:
          type: number
          example: '12'
        vendor:
          type: string
          example: "00a6fa25"
        productImages:
          type: array
          items: 
            type: string
      required:
        - uuid
        - category
        - name
        - description
        - vendor
        - stock

    EditProductRequest:
      type: object
      properties:
        category:
          type: string
        name:
          type: string
          example: "name"
        description: 
          type: string
          example: "description"
        stock:
          type: number
          example: '12'
        productImages:
          type: array
          items: 
            type: string


    VendorSchema:
      type: array
      items: 
        type: object
        properties:
          uuid:
            type: string
            example: "00a6fa25-df29-4701-9077-557932591766"
          name:
            type: string
            example: "name"
          email:
            type: string
            format: email
          address:
            type: array
            items: 
              type: object
              properties:
                area: 
                  type: string
                city:
                  type: string
                state:
                  type: string
                pincode:
                  type: string
          phone:
            type: string
          profileImage:
            type: string
          role:
            type: string
            default: vendor
